[versions]
agp = "8.9.2"
kotlin = "2.0.21"

coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

installReferrer = "2.2"

[libraries]

# Android Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Install Referrer (IMPORTANT for SDK)
installreferrer = { group = "com.android.installreferrer", name = "installreferrer", version.ref = "installReferrer" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }